defaults: &defaults
  docker:
  - image: circleci/node:8

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Test application
          command: yarn test
      - store_artifacts:
          path: dist/docs/jest/junit.xml
          prefix: tests
      - store_test_results:
          path: dist/docs

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "f2:b7:fc:0c:25:a9:77:fe:ea:59:fa:27:c3:43:3b:90"
      - run:
          name: Configure git and push to github page
          command: |
            git config user.email "$GH_EMAIL"
            git config user.name "$GH_NAME"
            yarn build
            yarn deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master